// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/dushixiang/pika/internal/config"
	"github.com/dushixiang/pika/internal/handler"
	"github.com/dushixiang/pika/internal/repo"
	"github.com/dushixiang/pika/internal/service"
	"github.com/dushixiang/pika/internal/websocket"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp(logger *zap.Logger, db *gorm.DB, cfg *config.AppConfig) (*AppComponents, error) {
	userRepo := repo.NewUserRepo(db)
	userService := service.NewUserService(logger, userRepo)
	accountService := provideAccountService(logger, userService, cfg)
	accountHandler := handler.NewAccountHandler(accountService)
	agentRepo := repo.NewAgentRepo(db)
	metricRepo := repo.NewMetricRepo(db)
	apiKeyRepo := provideApiKeyRepo(db)
	apiKeyService := provideApiKeyService(logger, apiKeyRepo)
	agentService := provideAgentService(logger, agentRepo, metricRepo, apiKeyService)
	manager := websocket.NewManager(logger)
	agentHandler := provideAgentHandler(logger, agentService, manager, cfg)
	userHandler := handler.NewUserHandler(userService)
	apiKeyHandler := provideApiKeyHandler(logger, apiKeyService)
	alertRepo := provideAlertRepo(db)
	notifier := provideNotifier(logger)
	alertService := provideAlertService(alertRepo, agentRepo, notifier, logger)
	alertHandler := provideAlertHandler(logger, alertService)
	appComponents := &AppComponents{
		AccountHandler: accountHandler,
		AgentHandler:   agentHandler,
		UserHandler:    userHandler,
		ApiKeyHandler:  apiKeyHandler,
		AlertHandler:   alertHandler,
		AgentService:   agentService,
		UserService:    userService,
		AlertService:   alertService,
		WSManager:      manager,
	}
	return appComponents, nil
}

// wire.go:

// AppComponents 应用组件
type AppComponents struct {
	AccountHandler *handler.AccountHandler
	AgentHandler   *handler.AgentHandler
	UserHandler    *handler.UserHandler
	ApiKeyHandler  *handler.ApiKeyHandler
	AlertHandler   *handler.AlertHandler
	AgentService   *service.AgentService
	UserService    *service.UserService
	AlertService   *service.AlertService
	WSManager      *websocket.Manager
}
